-- POSTGRES

CREATE DATABASE firstdb;


--  tabla programa
CREATE TABLE programa (
    programa_id SERIAL PRIMARY KEY,
    facultad_id INTEGER,
    nombre VARCHAR(100),
    cod_programa VARCHAR(100),
    tipo VARCHAR(10)
);

-- tabla facultad


CREATE TABLE IF NOT EXISTS facultad (
    facultad_id SERIAL PRIMARY KEY,
    nombre VARCHAR(100),
    abreviatura VARCHAR(20),
    id_area INTEGER
);

-- tabla USUARIO

CREATE TABLE IF NOT EXISTS users (
    usuario_id SERIAL PRIMARY KEY,
    username VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    password VARCHAR(100),
    rol VARCHAR(100) DEFAULT 'user'
);

-- CREAR VISTA PARA USUARIO LOGIN

CREATE OR REPLACE VIEW vw_usuario_login AS
SELECT usuario_id, email, password FROM users;


-- CREAR VISTA PARA REPORTE DE PROGRAMAS Y FACULTADES

CREATE OR REPLACE VIEW vw_programas_facultades AS 
SELECT ROW_NUMBER() OVER (ORDER BY dfa.facultad_id) AS numero_registro,
	dfa.abreviatura AS Abreviatura, dpr.nombre AS Programas
FROM facultad AS dfa
	INNER JOIN programa AS dpr
	ON dfa.facultad_id = dpr.facultad_id;



-- insert data 


INSERT INTO `programas` (`programa_id`, `facultad_id`, `nombre`, `cod_programa`, `tipo`) VALUES
	(1, 7, 'DESARROLLO RURAL', 'M01', 1),
	(2, 7, 'LINGÜÍSTICA ANDINA Y EDUCACIÓN', 'M04', 1),
	(3, 4, 'CONTABILIDAD Y ADMINISTRACIÓN', 'M05', 1),
	(4, 3, 'ECONOMÍA', 'M06', 1),
	(5, 15, 'EXTRACCIÓN DE METALES ESTRATÉGICOS', 'M07', 1),
	(6, 12, 'DERECHO', 'M08', 1),
	(7, 11, 'INFORMÁTICA', 'M09', 1),
	(8, 13, 'CIENCIAS: INGENIERÍA QUÍMICA', 'M10', 1),
	(9, 6, 'SALUD PUBLICA', 'M11', 1),
	(10, 7, 'CIENCIAS SOCIALES', 'M12', 1),
	(11, 10, 'EDUCACIÓN', 'M13', 1),
	(12, 15, 'TECNOLOGÍAS DE PROTECCIÓN AMBIENTAL', 'M14', 1),
	(13, 17, 'CIENCIAS DE LA INGENIERÍA AGRÍCOLA', 'M15', 1),
	(14, 9, 'ECOLOGÍA', 'M16', 1),
	(15, 5, 'TRABAJO SOCIAL', 'M18', 1),
	(16, 8, 'GEOTECNIA Y GEOMECANICA MINERA', 'M19', 1),
	(17, 14, 'CIENCIAS DE LA NUTRICIÓN', 'M20', 1),
	(18, 19, 'CIENCIAS DE LA INGENIERÍA MECÁNICA ELÉCTRICA', 'M21', 1),
	(19, 2, 'CIENCIA ANIMAL', 'M24', 1),
	(20, 16, 'ARQUITECTURA', 'M34', 1),
	(21, 19, 'INGENIERÍA DE SISTEMAS', 'M35', 1),
	(22, 16, 'INGENIERÍA CIVIL', 'M39', 1),
	(23, 7, 'INVESTIGACIÓN Y DOCENCIA UNIVERSITARIA', 'M41', 1),
	(24, 2, 'CIENCIA ANIMAL\r\n', 'D016', 2),
	(25, 3, 'ECONOMÍA Y POLÍTICAS PÚBLICAS\r\n', 'D011', 2),
	(26, 4, 'CONTABILIDAD Y FINANZAS\r\n', 'D009', 2),
	(27, 4, 'ADMINISTRACIÓN', 'D008', 2),
	(28, 8, 'CIENCIA, TECNOLOGÍA Y MEDIO AMBIENTE\r\n', 'D001', 2),
	(29, 7, 'CIENCIAS SOCIALES, GESTIÓN PÚBLICA Y DESARROLLO TERRITORIAL', 'D017', 2),
	(30, 10, 'EDUCACIÓN', 'D007', 2),
	(31, 11, 'CIENCIAS DE LA COMPUTACIÓN\r\n', 'D013', 2),
	(32, 11, 'ESTADÍSTICA APLICADA\r\n', 'D015', 2),
	(33, 11, 'ESTADÍSTICA E INFORMÁTICA\r\n', 'D014', 2),
	(34, 12, 'DERECHO', 'D006', 2),
	(36, 14, 'CIENCIAS DE LA SALUD', 'D005', 2),
	(37, 19, 'CIENCIAS DE LA INGENIERÍA MECÁNICA ELÉCTRICA', 'D022', 2),
	(38, 7, 'CIENCIAS SOCIALES', 'OFICIO Nº 0288-2020-D-PD-EPG-UNA', 2),
	(39, 3, 'ECONOMIA Y DESARROLLO SOSTENIBLE', 'OFICIO Nº 0288-2020-D-PD-EPG-UNA', 2),
	(40, 3, 'ECONOMÍA Y GESTIÓN', 'OFICIO Nº 0288-2020-D-PD-EPG-UNA', 2),
	(41, 4, 'CONTABILIDAD Y ADMINISTRACIÓN', 'OFICIO Nº 0288-2020-D-PD-EPG-UNA', 2),
	(42, 7, 'CIENCIAS POLÍTICAS Y GOBERNANZA', 'OFICIO Nº 0288-2020-D-PD-EPG-UNA', 2);


INSERT INTO facultad (facultad_id, nombre, abreviatura, id_area) VALUES
	(1, 'CIENCIAS AGRARIAS', 'FCA', 1),
	(2, 'MEDICINA VETERINARIA Y ZOOTECNIA', 'FMVZ', 2),
	(3, 'INGENIERÍA ECONÓMICA', 'FIE', 3),
	(4, 'CIENCIAS CONTABLES Y ADMINISTRATIVAS', 'FCCA', 3),
	(5, 'TRABAJO SOCIAL', 'FTS', 4),
	(6, 'ENFERMERÍA', 'FE', 2),
	(7, 'CIENCIAS SOCIALES', 'FCS', 4),
	(8, 'INGENIERÍA DE MINAS', 'FIM', 1),
	(9, 'CIENCIAS BIOLÓGICAS', 'FCCBB', 2),
	(10, 'CIENCIAS DE LA EDUCACIÓN', 'FCEDUC', 4),
	(11, 'INGENIERÍA ESTADÍSTICA E INFORMÁTICA', 'FINESI', 1),
	(12, 'CIENCIAS JURÍDICAS Y POLÍTICAS', 'FCJP', 4),
	(13, 'INGENIERÍA QUÍMICA', 'FIQ', 1),
	(14, 'CIENCIAS DE LA SALUD', 'FCDS', 2),
	(15, 'INGENIERÍA GEOLÓGICA Y METALÚRGICA', 'FIGIM', 1),
	(16, 'INGENIERÍA CIVIL Y ARQUITECTURA', 'FICA', 1),
	(17, 'INGENIERÍA AGRÍCOLA', 'FIA', 1),
	(18, 'MEDICINA HUMANA', 'FMH', 2),
	(19, 'INGENIERÍA MECÁNICA ELÉCTRICA, ELECTRÓNICA Y SISTEMAS', 'FIMEES', 1),
	(20, 'ESCUELA DE POSGRADO', 'EPG', 0);